name: ea1nk-dxspider
services:
  dxspider:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - "linux/arm64"
        - "linux/amd64"
      args:
        - SPIDER_VERSION=${CLUSTER_DXSPIDER_BRANCH}
        - SPIDER_USERNAME=${CLUSTER_DB_USER}
    privileged: true
    container_name: dxspider-node
    depends_on:
      spider_database:
        condition: service_healthy
    environment:
      - SPIDER_INSTALL_DIR=/spider
      - CLUSTER_CALLSIGN=${CLUSTER_CALLSIGN}
      - CLUSTER_LOCATOR=${CLUSTER_LOCATOR}
      - CLUSTER_QTH=${CLUSTER_QTH}
      - CLUSTER_SYSOP_NAME=${CLUSTER_SYSOP_NAME}
      - CLUSTER_SYSOP_CALLSIGN=${CLUSTER_SYSOP_CALLSIGN}
      - CLUSTER_SYSOP_EMAIL=${CLUSTER_SYSOP_EMAIL}
      - CLUSTER_SYSOP_BBS_ADDRESS=${CLUSTER_SYSOP_BBS_ADDRESS}
      - CLUSTER_LATITUDE=${CLUSTER_LATITUDE}
      - CLUSTER_LONGITUDE=${CLUSTER_LONGITUDE}
      - SPIDER_USERNAME=${CLUSTER_DB_USER}
      - CLUSTER_DSN=dbi:mysql:${CLUSTER_DB_NAME}:db:${CLUSTER_DB_PORT} # Cambiado 'hostname' por 'db'
      - CLUSTER_DBUSER=${CLUSTER_DB_USER}
      - CLUSTER_DBPASS=${CLUSTER_DB_PASS}
      - CLUSTER_PORT=${CLUSTER_PORT}
      - CLUSTER_SYSOP_PORT=${CLUSTER_SYSOP_PORT}
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "${CLUSTER_PORT}"]
      interval: 10s
      start_period: 10s
      retries: 3
      timeout: 5s
    restart: always
    volumes:
      - ./startup:/spider/scripts/startup:rw
      - ./crontab:/spider/local_cmd/crontab:rw
      - ./connect:/spider/connect:rw
      - ./motd:/spider/local_data/motd:rw
      - ./motd_nor:/spider/local_data/motd_nor:rw
      - ./local_data:/spider/local_data:rw
      - ./cmd:/spider/cmd:rw
      - ./msg:/spider/msg:rw
    ports:
      - "${CLUSTER_PORT}:${CLUSTER_PORT}"
      - "${CLUSTER_SYSOP_PORT}:${CLUSTER_SYSOP_PORT}"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  spider_database:  
    image: mariadb:10.11
    container_name: dxspider-db
    restart: always
    environment:
      MYSQL_DATABASE: ${CLUSTER_DB_NAME}
      MYSQL_USER: ${CLUSTER_DB_USER}
      MYSQL_PASSWORD: ${CLUSTER_DB_PASS}
      MYSQL_ROOT_PASSWORD: ${CLUSTER_DB_ROOT_PASSWORD:-rootpassword}
    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
  nginx:
      image: nginx:alpine
      container_name: dxspider-proxy
      restart: always
      ports:
        - "80:80"   # Puerto HTTP estándar
        - "443:443" # Para futuro SSL
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/conf.d:/etc/nginx/conf.d:ro
        - ./nginx/logs:/var/log/nginx
      depends_on:
        - dxspider
  web_server:
    image: nginx:alpine
    container_name: dxspider-webui
    volumes:
     - ./web_content:/usr/share/nginx/html:ro
