user  nginx;
worker_processes  auto;
error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;
    sendfile        on;
    keepalive_timeout  65;

    # Resolver DNS dinámico de Docker para que nginx no cachee IPs de upstream
    resolver 127.0.0.11 valid=10s;

    # Configuración del servidor Proxy
    server {
        listen 80;
        server_name localhost; # O tu dominio si tienes uno

        # 1. Redirigir la raíz a Spiderweb
        location / {
            set $webui http://dxspider-webui:8080;
            proxy_pass $webui;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # 2. Redirigir el tráfico a la WebUI de DXSpider (ttyd / Mojo)
        # Asumiendo que ttyd corre en el puerto 8000 dentro del contenedor dxspider
        location /console {
            proxy_pass http://dxspider-node:8050/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
